//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AC_Permissions
    {
        public AC_Permissions()
        {
            this.AC_PermissionMapping = new HashSet<AC_PermissionMapping>();
        }
    
        public int ID { get; set; }
        public string Permission { get; set; }
        public string Memo { get; set; }
    
        public virtual ICollection<AC_PermissionMapping> AC_PermissionMapping { get; set; }
    }
}
