//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AC_PersPasswordsProfile
    {
        public int Pers_Nr { get; set; }
        public string UserName { get; set; }
        public string CurrentPassword { get; set; }
        public string OldPassword { get; set; }
        public Nullable<int> ProfileID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
    }
}
