//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AC_ReportSettings
    {
        public long ID { get; set; }
        public Nullable<long> ReportID { get; set; }
        public Nullable<bool> ShowDate { get; set; }
        public Nullable<bool> ShowTime { get; set; }
        public Nullable<bool> ShowBuildingLocation { get; set; }
        public Nullable<bool> ShowBuilding { get; set; }
        public Nullable<bool> ShowFloor { get; set; }
        public Nullable<bool> ShowRoom { get; set; }
        public Nullable<bool> ShowReader { get; set; }
        public Nullable<bool> ShowCompany { get; set; }
        public Nullable<bool> ShowPersLocation { get; set; }
        public Nullable<bool> ShowPersDepartment { get; set; }
        public Nullable<bool> ShowPersCC { get; set; }
        public Nullable<bool> ShowPersName { get; set; }
        public Nullable<bool> ShowPersCardNrLong { get; set; }
        public Nullable<bool> ShowPersCardNrShort { get; set; }
        public Nullable<int> PrintSelection { get; set; }
    
        public virtual AC_Reports AC_Reports { get; set; }
    }
}
