//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AC_Reports
    {
        public AC_Reports()
        {
            this.AC_ReportSettings = new HashSet<AC_ReportSettings>();
        }
    
        public long ID { get; set; }
        public long Nr { get; set; }
        public string Name { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string StartLocationB { get; set; }
        public string EndLocationB { get; set; }
        public string StartBuilding { get; set; }
        public string EndBuilding { get; set; }
        public string StartLevel { get; set; }
        public string EndLevel { get; set; }
        public string StartRoom { get; set; }
        public string EndRoom { get; set; }
        public string StartDoor { get; set; }
        public string EndDoor { get; set; }
        public Nullable<int> StartClient { get; set; }
        public Nullable<int> EndClient { get; set; }
        public Nullable<int> StartLocation { get; set; }
        public Nullable<int> EndLocation { get; set; }
        public Nullable<int> StartDept { get; set; }
        public Nullable<int> EndDept { get; set; }
        public Nullable<int> StartCostCenter { get; set; }
        public Nullable<int> EndCostCenter { get; set; }
        public Nullable<int> StartPersonal { get; set; }
        public Nullable<int> EndPersonal { get; set; }
        public Nullable<int> StartShortTransponder { get; set; }
        public Nullable<int> EndShortTranspoder { get; set; }
        public Nullable<int> StartLongTranspoder { get; set; }
        public Nullable<int> EndLongTransponder { get; set; }
        public Nullable<int> StartMemberGroup { get; set; }
        public Nullable<int> EndMemberGroup { get; set; }
    
        public virtual ICollection<AC_ReportSettings> AC_ReportSettings { get; set; }
    }
}
