//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessPlanGroupDoorMapping
    {
        public long ID { get; set; }
        public Nullable<long> AccessPlanGroupID { get; set; }
        public Nullable<long> BuildingPlanID { get; set; }
        public Nullable<long> LocationID { get; set; }
        public Nullable<long> BuildingID { get; set; }
        public Nullable<long> FloorID { get; set; }
        public Nullable<long> RoomID { get; set; }
        public Nullable<long> DoorID { get; set; }
    
        public virtual BuildingPlan BuildingPlan { get; set; }
        public virtual TbAccessPlanGroup TbAccessPlanGroup { get; set; }
    }
}
