//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessProfileAccessGroupMapping
    {
        public long ID { get; set; }
        public long AccessProfileID { get; set; }
        public long AccessGroupID { get; set; }
    
        public virtual AccessGroup AccessGroup { get; set; }
        public virtual ZuttritProfile ZuttritProfile { get; set; }
    }
}
