//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessCalendarProfile
    {
        public long ID { get; set; }
        public Nullable<long> AccessCalendarID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<long> AccessProfile { get; set; }
    }
}
