//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BreaksType
    {
        public long ID { get; set; }
        public long TpyeNr { get; set; }
        public string Abbriviation { get; set; }
        public string Description { get; set; }
    }
}
