//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BreaksMapped
    {
        public int ID { get; set; }
        public int DP_Nr { get; set; }
        public int Break_Nr { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public System.DateTime TimeFrom { get; set; }
        public System.DateTime TimeTo { get; set; }
        public string Memo { get; set; }
        public string MinDiff { get; set; }
        public int Break_ID { get; set; }
    }
}
