//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CellPhoneMaster
    {
        public int ID { get; set; }
        public string CellID { get; set; }
        public string Name { get; set; }
        public Nullable<int> MobileNumber { get; set; }
        public string MobileIdentification { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string Username { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<System.DateTime> OutputOn { get; set; }
        public string ContractingParty { get; set; }
        public Nullable<System.DateTime> Inception { get; set; }
        public Nullable<System.DateTime> ContractEnd { get; set; }
        public string LeaseTerm { get; set; }
        public string Tariff { get; set; }
        public string TariffPricePerMonth { get; set; }
        public Nullable<bool> TimeTracking { get; set; }
        public Nullable<bool> CostCenter { get; set; }
        public Nullable<bool> CostandFlexCostCenter { get; set; }
        public Nullable<bool> ProjectTracking { get; set; }
        public Nullable<bool> Customer { get; set; }
        public Nullable<bool> Project { get; set; }
        public Nullable<bool> IsOrder { get; set; }
    }
}
