//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CostCenter
    {
        public CostCenter()
        {
            this.EmployeeInfoes = new HashSet<EmployeeInfo>();
            this.Pers_CostCenters = new HashSet<Pers_CostCenters>();
        }
    
        public long ID { get; set; }
        public string Name { get; set; }
        public Nullable<long> CostCenter_Nr { get; set; }
        public string Ort { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string Street { get; set; }
        public string HouseNumber { get; set; }
        public long LocationId { get; set; }
        public string LocationHeadName { get; set; }
        public string LocationHeadFunction { get; set; }
        public string LocationHeadPhone { get; set; }
        public string LocationHeadMobile { get; set; }
        public string LocationHeadEmail { get; set; }
        public string InfoText { get; set; }
    
        public virtual ICollection<EmployeeInfo> EmployeeInfoes { get; set; }
        public virtual ICollection<Pers_CostCenters> Pers_CostCenters { get; set; }
    }
}
