//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyCalendar
    {
        public DailyCalendar()
        {
            this.PlannedCalendars = new HashSet<PlannedCalendar>();
        }
    
        public long Id { get; set; }
        public long CalendarId { get; set; }
        public System.TimeSpan Monday { get; set; }
        public System.TimeSpan Tuesday { get; set; }
        public System.TimeSpan Wednesday { get; set; }
        public System.TimeSpan Thursday { get; set; }
        public System.TimeSpan Friday { get; set; }
        public System.TimeSpan Saturday { get; set; }
        public System.TimeSpan Sunday { get; set; }
    
        public virtual PlannedCalendar PlannedCalendar { get; set; }
        public virtual ICollection<PlannedCalendar> PlannedCalendars { get; set; }
    }
}
