//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyProgram
    {
        public DailyProgram()
        {
            this.DP_Shifts = new HashSet<DP_Shifts>();
            this.Shifts = new HashSet<Shift>();
        }
    
        public int ID { get; set; }
        public long DP_Id { get; set; }
        public string DP_Nr { get; set; }
        public string Name { get; set; }
        public System.DateTime HourFrom { get; set; }
        public System.DateTime HourTo { get; set; }
    
        public virtual ICollection<DP_Shifts> DP_Shifts { get; set; }
        public virtual ICollection<Shift> Shifts { get; set; }
    }
}
