//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyBooking
    {
        public long Id { get; set; }
        public long RawBookingId { get; set; }
        public long EmployeeId { get; set; }
        public int EmployeeNumber { get; set; }
        public System.DateTime BookingTime { get; set; }
        public System.DateTime DateProcessed { get; set; }
        public int BookingStatus { get; set; }
        public string Terminal { get; set; }
        public string Memo { get; set; }
        public Nullable<bool> ProcessingStatus { get; set; }
    }
}
