//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyProgramMapped
    {
        public DailyProgramMapped()
        {
            this.ResourceEventMappeds = new HashSet<ResourceEventMapped>();
        }
    
        public int ID { get; set; }
        public long DP_Id { get; set; }
        public string DP_Nr { get; set; }
        public string Name { get; set; }
        public System.DateTime HourFrom { get; set; }
        public System.DateTime HourTo { get; set; }
    
        public virtual ICollection<ResourceEventMapped> ResourceEventMappeds { get; set; }
    }
}
