//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyBookingsReport
    {
        public int ID { get; set; }
        public int InfoNumber { get; set; }
        public string InfoName { get; set; }
        public string Accounts { get; set; }
        public Nullable<int> BookingsCount { get; set; }
        public Nullable<int> ReportPosition { get; set; }
    }
}
