//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatafoxTerminalInstance
    {
        public DatafoxTerminalInstance()
        {
            this.DatafoxTerminalReaders = new HashSet<DatafoxTerminalReader>();
        }
    
        public long ID { get; set; }
        public string TermType { get; set; }
        public int TermID { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string SerialNumber { get; set; }
        public string ConnectionType { get; set; }
        public string IpAddress { get; set; }
        public Nullable<int> Port { get; set; }
        public string Memo { get; set; }
        public Nullable<long> TerminalOEMId { get; set; }
        public Nullable<long> TerminalNewId { get; set; }
    
        public virtual ICollection<DatafoxTerminalReader> DatafoxTerminalReaders { get; set; }
    }
}
