//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DF_TIME
    {
        public Nullable<long> DF_KEY { get; set; }
        public long ID { get; set; }
        public Nullable<long> AccessProfID { get; set; }
        public int Weekdays { get; set; }
        public string TimeFrom { get; set; }
        public string TimeTo { get; set; }
    }
}
