//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DP_Shifts
    {
        public DP_Shifts()
        {
            this.Shift_Breaks = new HashSet<Shift_Breaks>();
        }
    
        public int ID { get; set; }
        public int Shift_Nr { get; set; }
        public int DP_ID { get; set; }
        public System.DateTime CountFrom { get; set; }
        public System.DateTime CountTo { get; set; }
        public string CountDesc { get; set; }
        public System.DateTime EvalFrom { get; set; }
        public System.DateTime EvalTo { get; set; }
        public string EvalDesc { get; set; }
    
        public virtual DailyProgram DailyProgram { get; set; }
        public virtual ICollection<Shift_Breaks> Shift_Breaks { get; set; }
    }
}
