//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeTariff
    {
        public long Id { get; set; }
        public int EmployeeId { get; set; }
        public long TariffId { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Tariff Tariff { get; set; }
    }
}
