//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeInfo
    {
        public EmployeeInfo()
        {
            this.Employees = new HashSet<Employee>();
        }
    
        public int ID { get; set; }
        public Nullable<System.DateTime> DoB { get; set; }
        public string PlaceOfBirth { get; set; }
        public string DrivingLicense { get; set; }
        public string BankAccNo { get; set; }
        public string Bank { get; set; }
        public string Gender { get; set; }
        public string MaritalStatus { get; set; }
        public Nullable<int> Children { get; set; }
        public string Nationality { get; set; }
        public string Denomination { get; set; }
        public string SSN { get; set; }
        public string FinanceAuthority { get; set; }
        public string TaxClass { get; set; }
        public string HealthInsurance { get; set; }
        public Nullable<double> HINumber { get; set; }
        public string Job { get; set; }
        public Nullable<double> NoOfHours { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ContPeriodFrom { get; set; }
        public Nullable<System.DateTime> ContPeriodTo { get; set; }
        public Nullable<System.DateTime> ResignedOn { get; set; }
        public Nullable<long> CostCenterId { get; set; }
        public long DepartmentId { get; set; }
        public long LocationId { get; set; }
        public string Street { get; set; }
        public string CarType { get; set; }
        public string CarReg { get; set; }
        public string CompanyName { get; set; }
        public string Town { get; set; }
        public string PhoneNumber { get; set; }
        public string Memo { get; set; }
        public string Position { get; set; }
        public string CompanyPhone { get; set; }
        public string CompanyMobile { get; set; }
        public string PersonalPhone { get; set; }
        public string PersonalMobile { get; set; }
        public string CompanyEmail { get; set; }
        public string PersonalEmail { get; set; }
    
        public virtual CostCenter CostCenter { get; set; }
        public virtual ICollection<Employee> Employees { get; set; }
    }
}
