//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERG_Konten
    {
        public string Kto_Index { get; set; }
        public Nullable<short> Kto_Jahr { get; set; }
        public Nullable<short> Kto_Monat { get; set; }
        public Nullable<int> Kto_Pers_Nr { get; set; }
        public Nullable<int> Kto_K_Nr { get; set; }
        public Nullable<double> T1 { get; set; }
        public Nullable<double> T2 { get; set; }
        public Nullable<double> T3 { get; set; }
        public Nullable<double> T4 { get; set; }
        public Nullable<double> T5 { get; set; }
        public Nullable<double> T6 { get; set; }
        public Nullable<double> T7 { get; set; }
        public Nullable<double> T8 { get; set; }
        public Nullable<double> T9 { get; set; }
        public Nullable<double> T10 { get; set; }
        public Nullable<double> T11 { get; set; }
        public Nullable<double> T12 { get; set; }
        public Nullable<double> T13 { get; set; }
        public Nullable<double> T14 { get; set; }
        public Nullable<double> T15 { get; set; }
        public Nullable<double> T16 { get; set; }
        public Nullable<double> T17 { get; set; }
        public Nullable<double> T18 { get; set; }
        public Nullable<double> T19 { get; set; }
        public Nullable<double> T20 { get; set; }
        public Nullable<double> T21 { get; set; }
        public Nullable<double> T22 { get; set; }
        public Nullable<double> T23 { get; set; }
        public Nullable<double> T24 { get; set; }
        public Nullable<double> T25 { get; set; }
        public Nullable<double> T26 { get; set; }
        public Nullable<double> T27 { get; set; }
        public Nullable<double> T28 { get; set; }
        public Nullable<double> T29 { get; set; }
        public Nullable<double> T30 { get; set; }
        public Nullable<double> T31 { get; set; }
        public Nullable<double> W1 { get; set; }
        public Nullable<double> W2 { get; set; }
        public Nullable<double> W3 { get; set; }
        public Nullable<double> W4 { get; set; }
        public Nullable<double> W5 { get; set; }
        public Nullable<double> W6 { get; set; }
        public Nullable<double> W7 { get; set; }
        public Nullable<double> W8 { get; set; }
        public Nullable<double> W9 { get; set; }
        public Nullable<double> W10 { get; set; }
        public Nullable<double> W11 { get; set; }
        public Nullable<double> W12 { get; set; }
        public Nullable<double> W13 { get; set; }
        public Nullable<double> W14 { get; set; }
        public Nullable<double> W15 { get; set; }
        public Nullable<double> W16 { get; set; }
        public Nullable<double> W17 { get; set; }
        public Nullable<double> W18 { get; set; }
        public Nullable<double> W19 { get; set; }
        public Nullable<double> W20 { get; set; }
        public Nullable<double> W21 { get; set; }
        public Nullable<double> W22 { get; set; }
        public Nullable<double> W23 { get; set; }
        public Nullable<double> W24 { get; set; }
        public Nullable<double> W25 { get; set; }
        public Nullable<double> W26 { get; set; }
        public Nullable<double> W27 { get; set; }
        public Nullable<double> W28 { get; set; }
        public Nullable<double> W29 { get; set; }
        public Nullable<double> W30 { get; set; }
        public Nullable<double> W31 { get; set; }
        public Nullable<double> M1 { get; set; }
        public Nullable<double> M2 { get; set; }
        public Nullable<double> M3 { get; set; }
        public Nullable<double> M4 { get; set; }
        public Nullable<double> M5 { get; set; }
        public Nullable<double> M6 { get; set; }
        public Nullable<double> M7 { get; set; }
        public Nullable<double> M8 { get; set; }
        public Nullable<double> M9 { get; set; }
        public Nullable<double> M10 { get; set; }
        public Nullable<double> M11 { get; set; }
        public Nullable<double> M12 { get; set; }
        public Nullable<double> M13 { get; set; }
        public Nullable<double> M14 { get; set; }
        public Nullable<double> M15 { get; set; }
        public Nullable<double> M16 { get; set; }
        public Nullable<double> M17 { get; set; }
        public Nullable<double> M18 { get; set; }
        public Nullable<double> M19 { get; set; }
        public Nullable<double> M20 { get; set; }
        public Nullable<double> M21 { get; set; }
        public Nullable<double> M22 { get; set; }
        public Nullable<double> M23 { get; set; }
        public Nullable<double> M24 { get; set; }
        public Nullable<double> M25 { get; set; }
        public Nullable<double> M26 { get; set; }
        public Nullable<double> M27 { get; set; }
        public Nullable<double> M28 { get; set; }
        public Nullable<double> M29 { get; set; }
        public Nullable<double> M30 { get; set; }
        public Nullable<double> M31 { get; set; }
        public Nullable<double> J1 { get; set; }
        public Nullable<double> J2 { get; set; }
        public Nullable<double> J3 { get; set; }
        public Nullable<double> J4 { get; set; }
        public Nullable<double> J5 { get; set; }
        public Nullable<double> J6 { get; set; }
        public Nullable<double> J7 { get; set; }
        public Nullable<double> J8 { get; set; }
        public Nullable<double> J9 { get; set; }
        public Nullable<double> J10 { get; set; }
        public Nullable<double> J11 { get; set; }
        public Nullable<double> J12 { get; set; }
        public Nullable<double> J13 { get; set; }
        public Nullable<double> J14 { get; set; }
        public Nullable<double> J15 { get; set; }
        public Nullable<double> J16 { get; set; }
        public Nullable<double> J17 { get; set; }
        public Nullable<double> J18 { get; set; }
        public Nullable<double> J19 { get; set; }
        public Nullable<double> J20 { get; set; }
        public Nullable<double> J21 { get; set; }
        public Nullable<double> J22 { get; set; }
        public Nullable<double> J23 { get; set; }
        public Nullable<double> J24 { get; set; }
        public Nullable<double> J25 { get; set; }
        public Nullable<double> J26 { get; set; }
        public Nullable<double> J27 { get; set; }
        public Nullable<double> J28 { get; set; }
        public Nullable<double> J29 { get; set; }
        public Nullable<double> J30 { get; set; }
        public Nullable<double> J31 { get; set; }
        public Nullable<System.DateTime> LASTACCESS { get; set; }
    }
}
