//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERP_Anrede
    {
        public ERP_Anrede()
        {
            this.ERP_KAnsprechp = new HashSet<ERP_KAnsprechp>();
            this.MembersDatas = new HashSet<MembersData>();
        }
    
        public int AnredeCode { get; set; }
        public string AnredeName { get; set; }
        public string StdBriefAnrede { get; set; }
        public Nullable<int> NameorVorname { get; set; }
        public string Titel { get; set; }
        public Nullable<int> Nummer { get; set; }
        public Nullable<int> Weiblich { get; set; }
        public Nullable<int> Männlich { get; set; }
        public Nullable<int> AnredeCodeAlternativ { get; set; }
    
        public virtual ICollection<ERP_KAnsprechp> ERP_KAnsprechp { get; set; }
        public virtual ICollection<MembersData> MembersDatas { get; set; }
    }
}
