//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERP_KundenMark
    {
        public int Code { get; set; }
        public Nullable<int> BenutzerCode { get; set; }
        public Nullable<int> ObjCode { get; set; }
        public Nullable<int> KAnsprechpCode { get; set; }
        public Nullable<int> Markierung { get; set; }
        public Nullable<int> OriginalCode { get; set; }
    }
}
