//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERP_KundenGrMark
    {
        public int Code { get; set; }
        public Nullable<int> GrCode { get; set; }
        public Nullable<int> BCode { get; set; }
    }
}
