//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERP_KundenGr
    {
        public int GrCode { get; set; }
        public Nullable<int> GrIndex { get; set; }
        public Nullable<int> GrLevel { get; set; }
        public string GrName { get; set; }
        public string Info { get; set; }
    }
}
