//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERP_Länder
    {
        public int Code { get; set; }
        public string Kennzeichen { get; set; }
        public string Kennzeichen2 { get; set; }
        public string Kennzeichen3 { get; set; }
        public Nullable<int> Steuer { get; set; }
        public string Langtext { get; set; }
        public string Korrektur_LKZ { get; set; }
        public Nullable<int> Angelsächsisch { get; set; }
        public Nullable<double> ReisekostenÜber24h { get; set; }
        public Nullable<double> ReisekostenÜber14h { get; set; }
        public Nullable<double> ReisekostenÜber8h { get; set; }
        public Nullable<double> ÜbernachtungsPauschale { get; set; }
        public Nullable<double> Frühstück { get; set; }
        public string Telefonvorwahl { get; set; }
        public Nullable<int> Steuerschlüssel1 { get; set; }
        public Nullable<int> Steuerschlüssel2 { get; set; }
        public Nullable<int> Steuerschlüssel3 { get; set; }
        public Nullable<double> ReisekostenUnter24h { get; set; }
    }
}
