//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HardwareConfig
    {
        public int Id { get; set; }
        public bool TimeTrackingZK { get; set; }
        public bool TimeTrackingDataFox { get; set; }
        public bool TimeTrackingKaba { get; set; }
        public bool TimeTrackingMobile { get; set; }
        public bool AccessZK { get; set; }
        public bool AccessDataFox { get; set; }
        public bool AccessKaba { get; set; }
        public bool ProjectZK { get; set; }
        public bool ProjectDataFox { get; set; }
        public bool ProjectKaba { get; set; }
    }
}
