//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HolidayCalendar_with_DateTime
    {
        public Nullable<System.DateTime> Datum { get; set; }
        public long HolidayId { get; set; }
        public long CalendarId { get; set; }
    }
}
