//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HolidayPlanCalendarMonth
    {
        public long Id { get; set; }
        public long HolidayPlanCalendarId { get; set; }
        public int CalendarMonth { get; set; }
        public string Day1ProfileHolidayId { get; set; }
        public string Day2ProfileHolidayId { get; set; }
        public string Day3ProfileHolidayId { get; set; }
        public string Day4ProfileHolidayId { get; set; }
        public string Day5ProfileHolidayId { get; set; }
        public string Day6ProfileHolidayId { get; set; }
        public string Day7ProfileHolidayId { get; set; }
        public string Day8ProfileHolidayId { get; set; }
        public string Day9ProfileHolidayId { get; set; }
        public string Day10ProfileHolidayId { get; set; }
        public string Day11ProfileHolidayId { get; set; }
        public string Day12ProfileHolidayId { get; set; }
        public string Day13ProfileHolidayId { get; set; }
        public string Day14ProfileHolidayId { get; set; }
        public string Day15ProfileHolidayId { get; set; }
        public string Day16ProfileHolidayId { get; set; }
        public string Day17ProfileHolidayId { get; set; }
        public string Day18ProfileHolidayId { get; set; }
        public string Day19ProfileHolidayId { get; set; }
        public string Day20ProfileHolidayId { get; set; }
        public string Day21ProfileHolidayId { get; set; }
        public string Day22ProfileHolidayId { get; set; }
        public string Day23ProfileHolidayId { get; set; }
        public string Day24ProfileHolidayId { get; set; }
        public string Day25ProfileHolidayId { get; set; }
        public string Day26ProfileHolidayId { get; set; }
        public string Day27ProfileHolidayId { get; set; }
        public string Day28ProfileHolidayId { get; set; }
        public string Day29ProfileHolidayId { get; set; }
        public string Day30ProfileHolidayId { get; set; }
        public string Day31ProfileHolidayId { get; set; }
    
        public virtual HolidayPlanCalendar HolidayPlanCalendar { get; set; }
    }
}
