//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HolidayCalendar
    {
        public HolidayCalendar()
        {
            this.HolidayCalendarMonths = new HashSet<HolidayCalendarMonth>();
            this.HolidayPlanCalendars = new HashSet<HolidayPlanCalendar>();
        }
    
        public long Id { get; set; }
        public int CalendarYear { get; set; }
        public long HolidayCalendarNumber { get; set; }
        public string HolidayCalendarName { get; set; }
        public string Memo { get; set; }
    
        public virtual ICollection<HolidayCalendarMonth> HolidayCalendarMonths { get; set; }
        public virtual ICollection<HolidayPlanCalendar> HolidayPlanCalendars { get; set; }
    }
}
