//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JC_Activities
    {
        public int ID { get; set; }
        public string ActivityNo { get; set; }
        public string ActivityDescription { get; set; }
        public string ActivityContent { get; set; }
        public string FlexCosts { get; set; }
        public string RunningCosts { get; set; }
        public string Surcharge { get; set; }
        public string Profit { get; set; }
        public string FlexCostPercent { get; set; }
        public string RunningCostPercent { get; set; }
        public string TotalCost { get; set; }
        public string SurchargePercent { get; set; }
        public string ProfitPercent { get; set; }
        public int CurrencyID { get; set; }
        public string Comment { get; set; }
    
        public virtual JC_Currency JC_Currency { get; set; }
    }
}
