//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JC_Currency
    {
        public JC_Currency()
        {
            this.JC_Activities = new HashSet<JC_Activities>();
        }
    
        public int ID { get; set; }
        public string CurrencySymbol { get; set; }
        public string CurrencyCode { get; set; }
        public string CurrencyName { get; set; }
    
        public virtual ICollection<JC_Activities> JC_Activities { get; set; }
    }
}
