//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kostenstellen
    {
        public double Kos_Nr { get; set; }
        public string Kos_Bezeichnung { get; set; }
        public string Memo { get; set; }
        public Nullable<System.DateTime> LastAccess { get; set; }
        public Nullable<double> Kos_LohnK { get; set; }
        public Nullable<double> Kos_FlexK { get; set; }
        public Nullable<double> Kos_BetrK { get; set; }
        public Nullable<bool> Kos_MaLohnK { get; set; }
        public Nullable<int> Kos_Konto { get; set; }
    }
}
