//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mandanten
    {
        public int ID { get; set; }
        public Nullable<int> Man_Nummer { get; set; }
        public string Man_Firma1 { get; set; }
        public string Man_Firma2 { get; set; }
        public string Man_Strasse { get; set; }
        public string Man_Plz { get; set; }
        public string Man_Ort { get; set; }
        public string Man_Postfach { get; set; }
        public string Man_Telefon1 { get; set; }
        public string Man_Telefax { get; set; }
        public string Man_Telefon2 { get; set; }
        public Nullable<bool> Aktiv { get; set; }
        public string Info { get; set; }
        public string ServerPZE { get; set; }
        public string DBPZE { get; set; }
        public string ServerAZE { get; set; }
        public string DBAZE { get; set; }
        public string UserDBPZE { get; set; }
        public string PwdDBPZE { get; set; }
        public string UserDBAZE { get; set; }
        public string PwdDBAZE { get; set; }
    }
}
