//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MapCalendar
    {
        public MapCalendar()
        {
            this.MapCalendarMonths = new HashSet<MapCalendarMonth>();
        }
    
        public long ID { get; set; }
        public int CalendarYear { get; set; }
        public int MapCalendarNumber { get; set; }
        public string MapCalendarIdNumber { get; set; }
        public string MapCalendarName { get; set; }
        public string Memo { get; set; }
    
        public virtual ICollection<MapCalendarMonth> MapCalendarMonths { get; set; }
    }
}
