//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MapCalendarMapped
    {
        public MapCalendarMapped()
        {
            this.MapCalendarMonthMappeds = new HashSet<MapCalendarMonthMapped>();
            this.Tariffs = new HashSet<Tariff>();
        }
    
        public long Id { get; set; }
        public int CalendarYear { get; set; }
        public int MapCalendarNumber { get; set; }
        public string MapCalendarIdNumber { get; set; }
        public string MapCalendarName { get; set; }
        public string Memo { get; set; }
    
        public virtual ICollection<MapCalendarMonthMapped> MapCalendarMonthMappeds { get; set; }
        public virtual ICollection<Tariff> Tariffs { get; set; }
    }
}
