//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberDuration
    {
        public MemberDuration()
        {
            this.MembersDatas = new HashSet<MembersData>();
        }
    
        public long ID { get; set; }
        public Nullable<long> DurationNr { get; set; }
        public string Duration { get; set; }
    
        public virtual ICollection<MembersData> MembersDatas { get; set; }
    }
}
