//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberGroup
    {
        public long Id { get; set; }
        public long GroupNr { get; set; }
        public string GroupName { get; set; }
        public string PersonHead { get; set; }
        public string TrainerOne { get; set; }
        public string TrainerTwo { get; set; }
        public string TrainerThree { get; set; }
        public string TrainerFour { get; set; }
        public string TrainerFive { get; set; }
    }
}
