//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MembersTransponder
    {
        public long ID { get; set; }
        public long MemberID { get; set; }
        public long TransponderNr { get; set; }
        public Nullable<bool> TransponderStatus { get; set; }
        public Nullable<System.DateTime> ValidFrom { get; set; }
        public Nullable<System.DateTime> ValidTo { get; set; }
        public Nullable<System.DateTime> TransponderDeactivatedOn { get; set; }
        public Nullable<int> Action { get; set; }
        public string Memo { get; set; }
        public Nullable<int> TransponderType { get; set; }
        public Nullable<System.DateTime> ExtendedTo { get; set; }
    
        public virtual MembersData MembersData { get; set; }
    }
}
