//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuTable
    {
        public int AutoID { get; set; }
        public int TreeLevel { get; set; }
        public string Name { get; set; }
        public string Parent { get; set; }
        public string Root { get; set; }
        public int TreeDisplayPosition { get; set; }
        public string Version { get; set; }
    }
}
