//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonthlyCalendarMapped
    {
        public MonthlyCalendarMapped()
        {
            this.PlannedCalendarMappeds = new HashSet<PlannedCalendarMapped>();
        }
    
        public long Id { get; set; }
        public long CalendarId { get; set; }
        public double January { get; set; }
        public double February { get; set; }
        public double March { get; set; }
        public double April { get; set; }
        public double May { get; set; }
        public double June { get; set; }
        public double July { get; set; }
        public double August { get; set; }
        public double September { get; set; }
        public double October { get; set; }
        public double November { get; set; }
        public double December { get; set; }
    
        public virtual PlannedCalendarMapped PlannedCalendarMapped { get; set; }
        public virtual ICollection<PlannedCalendarMapped> PlannedCalendarMappeds { get; set; }
    }
}
