//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MV_AccessControlTransactionPersonel
    {
        public System.DateTime AccessTime { get; set; }
        public long Card_Nr { get; set; }
        public long Pers_Nr { get; set; }
        public string Name { get; set; }
        public string LocationName { get; set; }
        public string DepartmentName { get; set; }
        public string SerialNumber { get; set; }
        public string ReaderID { get; set; }
    }
}
