//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MV_TerminalReaderBuildingPlans
    {
        public string SerialNumber { get; set; }
        public string TerminalReaderID { get; set; }
        public long ModelReaderID { get; set; }
        public int ReaderID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<int> BuildingID { get; set; }
        public Nullable<int> FloorID { get; set; }
        public int DoorID { get; set; }
        public Nullable<int> RoomID { get; set; }
        public string PlanDefinition { get; set; }
    }
}
