//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pers_PinCode
    {
        public long ID { get; set; }
        public long Pers_Nr { get; set; }
        public string PinCode { get; set; }
        public Nullable<int> PinCodeType { get; set; }
        public Nullable<bool> PinCodeStatus { get; set; }
    }
}
