//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pers_Type
    {
        public Pers_Type()
        {
            this.Personals = new HashSet<Personal>();
        }
    
        public long ID { get; set; }
        public string Name { get; set; }
        public string Memo { get; set; }
        public string PersTypeColor { get; set; }
    
        public virtual ICollection<Personal> Personals { get; set; }
    }
}
