//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonalStammeList
    {
        public Nullable<int> Pers_Nr { get; set; }
        public string FullName { get; set; }
        public string Abt_Bezeichnung { get; set; }
        public string W_Bezeichnung { get; set; }
        public string Kos_Bezeichnung { get; set; }
        public int Abt_Nr { get; set; }
    }
}
