//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pers_Archive
    {
        public long ID { get; set; }
        public long Pers_Nr { get; set; }
        public string Title { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public Nullable<long> Card_Nr { get; set; }
        public bool CardActive { get; set; }
        public System.DateTime EntryDate { get; set; }
        public Nullable<System.DateTime> ExitDate { get; set; }
        public Nullable<long> PersType { get; set; }
        public bool Active { get; set; }
        public string Memo { get; set; }
        public Nullable<bool> Imported { get; set; }
        public System.DateTime ArchivedDate { get; set; }
        public long ArchivedBy { get; set; }
    }
}
