//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pers_DynamicFields
    {
        public long ID { get; set; }
        public Nullable<long> Pers_Nr { get; set; }
        public Nullable<int> FieldIndex { get; set; }
        public string FieldValue { get; set; }
    }
}
