//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlannedCalendarMapped
    {
        public PlannedCalendarMapped()
        {
            this.DailyCalendarMappeds = new HashSet<DailyCalendarMapped>();
            this.MonthlyCalendarMappeds = new HashSet<MonthlyCalendarMapped>();
            this.PlannedCalendarTimeMappeds = new HashSet<PlannedCalendarTimeMapped>();
            this.Tariffs = new HashSet<Tariff>();
        }
    
        public long Id { get; set; }
        public int CalendarYear { get; set; }
        public string CalendarType { get; set; }
        public int CalendarNumber { get; set; }
        public string CalendarIdNumber { get; set; }
        public string CalendarName { get; set; }
        public bool Monday { get; set; }
        public bool Tuesday { get; set; }
        public bool Wednesday { get; set; }
        public bool Thursday { get; set; }
        public bool Friday { get; set; }
        public bool Saturday { get; set; }
        public bool Sunday { get; set; }
        public string Memo { get; set; }
        public Nullable<long> DailyCalendarId { get; set; }
        public Nullable<long> MonthlyCalendarId { get; set; }
    
        public virtual ICollection<DailyCalendarMapped> DailyCalendarMappeds { get; set; }
        public virtual DailyCalendarMapped DailyCalendarMapped { get; set; }
        public virtual ICollection<MonthlyCalendarMapped> MonthlyCalendarMappeds { get; set; }
        public virtual MonthlyCalendarMapped MonthlyCalendarMapped { get; set; }
        public virtual ICollection<PlannedCalendarTimeMapped> PlannedCalendarTimeMappeds { get; set; }
        public virtual ICollection<Tariff> Tariffs { get; set; }
    }
}
