//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlannedCalendar
    {
        public PlannedCalendar()
        {
            this.DailyCalendars = new HashSet<DailyCalendar>();
            this.MonthlyCalendars = new HashSet<MonthlyCalendar>();
            this.PlannedCalendarTimes = new HashSet<PlannedCalendarTime>();
        }
    
        public long Id { get; set; }
        public int CalendarYear { get; set; }
        public string CalendarType { get; set; }
        public int CalendarNumber { get; set; }
        public string CalendarIdNumber { get; set; }
        public string CalendarName { get; set; }
        public bool Monday { get; set; }
        public bool Tuesday { get; set; }
        public bool Wednesday { get; set; }
        public bool Thursday { get; set; }
        public bool Friday { get; set; }
        public bool Saturday { get; set; }
        public bool Sunday { get; set; }
        public string Memo { get; set; }
        public Nullable<long> DailyCalendarId { get; set; }
        public Nullable<long> MonthlyCalendarId { get; set; }
    
        public virtual ICollection<DailyCalendar> DailyCalendars { get; set; }
        public virtual DailyCalendar DailyCalendar { get; set; }
        public virtual ICollection<MonthlyCalendar> MonthlyCalendars { get; set; }
        public virtual MonthlyCalendar MonthlyCalendar { get; set; }
        public virtual ICollection<PlannedCalendarTime> PlannedCalendarTimes { get; set; }
    }
}
