//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Portal_ProfileUSerMapping
    {
        public long ID { get; set; }
        public long USerID { get; set; }
        public long ProfileID { get; set; }
    
        public virtual Portal_PermissionProfile Portal_PermissionProfile { get; set; }
        public virtual Portal_Users Portal_Users { get; set; }
    }
}
