//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Portal_PermissionMapping
    {
        public long ID { get; set; }
        public long PermissionKey { get; set; }
        public long PermissionType { get; set; }
        public long ProfileID { get; set; }
    
        public virtual Portal_PermissionProfile Portal_PermissionProfile { get; set; }
        public virtual Portal_Permissions Portal_Permissions { get; set; }
    }
}
