//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RawBooking
    {
        public int ID { get; set; }
        public int EmpID { get; set; }
        public System.DateTime Date { get; set; }
        public string EmpIDDate { get; set; }
        public Nullable<int> TermID { get; set; }
        public string TermSlot { get; set; }
        public string TimeSlot { get; set; }
    }
}
