//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReaderVisitorPlan
    {
        public long ID { get; set; }
        public Nullable<long> ReaderId { get; set; }
        public Nullable<long> VisitorPlanId { get; set; }
        public Nullable<bool> AccessPlanReaderStatus { get; set; }
        public Nullable<long> BuildingPlanID { get; set; }
        public Nullable<int> DoorID { get; set; }
    
        public virtual TbVisitorPlan TbVisitorPlan { get; set; }
        public virtual TerminalReader TerminalReader { get; set; }
    }
}
