//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReaderAssigned
    {
        public long ID { get; set; }
        public long BuildingPlanID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<int> BuildingID { get; set; }
        public Nullable<int> FloorID { get; set; }
        public Nullable<int> RoomID { get; set; }
        public int DoorID { get; set; }
        public long TerminalID { get; set; }
        public long ReaderID { get; set; }
        public int ConnectionID { get; set; }
        public bool Assigned { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> AccessProfileActive { get; set; }
        public Nullable<bool> SwitchProfileActive { get; set; }
        public Nullable<bool> ManualOpeningActive { get; set; }
        public Nullable<int> PassBackNr { get; set; }
        public Nullable<bool> TA_Come { get; set; }
        public Nullable<bool> TA_Go { get; set; }
    
        public virtual BuildingPlan BuildingPlan { get; set; }
        public virtual TerminalReader TerminalReader { get; set; }
    }
}
