//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RealTimeSetting
    {
        public int ID { get; set; }
        public Nullable<int> CalculationMode { get; set; }
        public Nullable<int> RefreshInterval { get; set; }
        public string ServerURL { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> BookingInterval { get; set; }
        public Nullable<int> Account1 { get; set; }
        public Nullable<int> Account2 { get; set; }
        public Nullable<int> Account3 { get; set; }
        public Nullable<int> Account4 { get; set; }
        public Nullable<int> Mandant { get; set; }
    }
}
