//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResourceEventMapped
    {
        public int ID { get; set; }
        public int ResourceId { get; set; }
        public int DailyProgramId { get; set; }
        public Nullable<long> ShiftId { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan EndTime { get; set; }
        public string Description { get; set; }
        public Nullable<int> BreakId { get; set; }
    
        public virtual DailyProgramMapped DailyProgramMapped { get; set; }
        public virtual ShiftResource ShiftResource { get; set; }
        public virtual Shift Shift { get; set; }
    }
}
