//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResourceEvent
    {
        public long ID { get; set; }
        public int ResourceId { get; set; }
        public Nullable<long> ShiftId { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public string Description { get; set; }
        public long BreakId { get; set; }
    
        public virtual ShiftResource ShiftResource { get; set; }
        public virtual Shift Shift { get; set; }
    }
}
