//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RV_AccessPlanPersonnel
    {
        public Nullable<long> AccessPlanNr { get; set; }
        public string AccessPlanDescription { get; set; }
        public long Pers_Nr { get; set; }
        public Nullable<long> Card_Nr { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string CostCenterName { get; set; }
        public string LocationName { get; set; }
        public string DepartmentName { get; set; }
    }
}
