//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RV_AccessPlanAccessCalendar
    {
        public long AccessPlanNr { get; set; }
        public string AccessPlanDescription { get; set; }
        public int Calendar_Nr { get; set; }
        public string Calendar_Name { get; set; }
        public long AccessProfileID { get; set; }
        public int AccessCalendarMonthNr { get; set; }
        public string Day1ProfileAccessProfileID { get; set; }
        public string Day2ProfileAccessProfileID { get; set; }
        public string Day3ProfileAccessProfileID { get; set; }
        public string Day4ProfileAccessProfileID { get; set; }
        public string Day5ProfileAccessProfileID { get; set; }
        public string Day6ProfileAccessProfileID { get; set; }
        public string Day7ProfileAccessProfileID { get; set; }
        public string Day8ProfileAccessProfileID { get; set; }
        public string Day9ProfileAccessProfileID { get; set; }
        public string Day10ProfileAccessProfileID { get; set; }
        public string Day11ProfileAccessProfileID { get; set; }
        public string Day12ProfileAccessProfileID { get; set; }
        public string Day13ProfileAccessProfileID { get; set; }
        public string Day14ProfileAccessProfileID { get; set; }
        public string Day15ProfileAccessProfileID { get; set; }
        public string Day16ProfileAccessProfileID { get; set; }
        public string Day17ProfileAccessProfileID { get; set; }
        public string Day18ProfileAccessProfileID { get; set; }
        public string Day19ProfileAccessProfileID { get; set; }
        public string Day20ProfileAccessProfileID { get; set; }
        public string Day21ProfileAccessProfileID { get; set; }
        public string Day22ProfileAccessProfileID { get; set; }
        public string Day23ProfileAccessProfileID { get; set; }
        public string Day24ProfileAccessProfileID { get; set; }
        public string Day25ProfileAccessProfileID { get; set; }
        public string Day26ProfileAccessProfileID { get; set; }
        public string Day27ProfileAccessProfileID { get; set; }
        public string Day28ProfileAccessProfileID { get; set; }
        public string Day29ProfileAccessProfileID { get; set; }
        public string Day30ProfileAccessProfileID { get; set; }
        public string Day31ProfileAccessProfileID { get; set; }
    }
}
