//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RV_HolidayPlanAccessPlan
    {
        public long ID { get; set; }
        public int TermID { get; set; }
        public string Description { get; set; }
        public string TermType { get; set; }
        public long AccessPlanID { get; set; }
        public long AccessPlanNumber { get; set; }
        public string AccessPlanDescription { get; set; }
        public long HolidayPlanID { get; set; }
        public long HolidayPlanNumber { get; set; }
        public string HolidayPlanName { get; set; }
        public int CalendarYear { get; set; }
        public int CalendarMonth { get; set; }
        public string Day1Holiday { get; set; }
        public string Day2Holiday { get; set; }
        public string Day3Holiday { get; set; }
        public string Day4Holiday { get; set; }
        public string Day5Holiday { get; set; }
        public string Day6Holiday { get; set; }
        public string Day7Holiday { get; set; }
        public string Day8Holiday { get; set; }
        public string Day9Holiday { get; set; }
        public string Day10Holiday { get; set; }
        public string Day11Holiday { get; set; }
        public string Day12Holiday { get; set; }
        public string Day13Holiday { get; set; }
        public string Day14Holiday { get; set; }
        public string Day15Holiday { get; set; }
        public string Day16Holiday { get; set; }
        public string Day17Holiday { get; set; }
        public string Day18Holiday { get; set; }
        public string Day19Holiday { get; set; }
        public string Day20Holiday { get; set; }
        public string Day21Holiday { get; set; }
        public string Day22Holiday { get; set; }
        public string Day23Holiday { get; set; }
        public string Day24Holiday { get; set; }
        public string Day25Holiday { get; set; }
        public string Day26Holiday { get; set; }
        public string Day27Holiday { get; set; }
        public string Day28Holiday { get; set; }
        public string Day29Holiday { get; set; }
        public string Day30Holiday { get; set; }
        public string Day31Holiday { get; set; }
    }
}
