//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RV_HolidayPlanAccessProfilesPerTerminal
    {
        public long ID { get; set; }
        public int TermID { get; set; }
        public string Description { get; set; }
        public string TermType { get; set; }
        public long AccessPlanID { get; set; }
        public long AccessPlanNumber { get; set; }
        public string AccessPlanDescription { get; set; }
        public long HolidayPlanID { get; set; }
        public long HolidayPlanNumber { get; set; }
        public string HolidayPlanName { get; set; }
        public int CalendarYear { get; set; }
        public int CalendarMonth { get; set; }
        public Nullable<long> AccessProfileID { get; set; }
        public int AccessProfileNo { get; set; }
        public string Memo { get; set; }
        public bool ProfilAktiv { get; set; }
        public System.DateTime MonFrom { get; set; }
        public System.DateTime MonTo { get; set; }
        public System.DateTime TueFrom { get; set; }
        public System.DateTime TueTo { get; set; }
        public System.DateTime WedFrom { get; set; }
        public System.DateTime WedTo { get; set; }
        public System.DateTime ThurFrom { get; set; }
        public System.DateTime ThurTo { get; set; }
        public System.DateTime FriFrom { get; set; }
        public System.DateTime FriTo { get; set; }
        public System.DateTime SatFrom { get; set; }
        public System.DateTime SatTo { get; set; }
        public System.DateTime SunFrom { get; set; }
        public System.DateTime SunTo { get; set; }
    }
}
