//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RV_HolidayCalendarAccessPlan
    {
        public long AccessPlanNr { get; set; }
        public long HolidayPlanCalendarNumber { get; set; }
        public string HolidayPlanCalendarName { get; set; }
        public int CalendarMonth { get; set; }
        public string Day1ProfileName { get; set; }
        public string Day2ProfileName { get; set; }
        public string Day3ProfileName { get; set; }
        public string Day4ProfileName { get; set; }
        public string Day5ProfileName { get; set; }
        public string Day6ProfileName { get; set; }
        public string Day7ProfileName { get; set; }
        public string Day8ProfileName { get; set; }
        public string Day9ProfileName { get; set; }
        public string Day10ProfileName { get; set; }
        public string Day11ProfileName { get; set; }
        public string Day12ProfileName { get; set; }
        public string Day13ProfileName { get; set; }
        public string Day14ProfileName { get; set; }
        public string Day15ProfileName { get; set; }
        public string Day16ProfileName { get; set; }
        public string Day17ProfileName { get; set; }
        public string Day18ProfileName { get; set; }
        public string Day19ProfileName { get; set; }
        public string Day20ProfileName { get; set; }
        public string Day21ProfileName { get; set; }
        public string Day22ProfileName { get; set; }
        public string Day23ProfileName { get; set; }
        public string Day24ProfileName { get; set; }
        public string Day25ProfileName { get; set; }
        public string Day26ProfileName { get; set; }
        public string Day27ProfileName { get; set; }
        public string Day28ProfileName { get; set; }
        public string Day29ProfileName { get; set; }
        public string Day30ProfileName { get; set; }
        public string Day31ProfileName { get; set; }
    }
}
