//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RV_SwitchPlanSwitchCalendar
    {
        public long SwitchPlanNumber { get; set; }
        public string SwitchPlanName { get; set; }
        public string SwitchCalendarNumber { get; set; }
        public string SwitchCalendarName { get; set; }
        public int CalendarMonth { get; set; }
        public string Day1SwitchProfileID { get; set; }
        public string Day2SwitchProfileID { get; set; }
        public string Day3SwitchProfileID { get; set; }
        public string Day4SwitchProfileID { get; set; }
        public string Day5SwitchProfileID { get; set; }
        public string Day6SwitchProfileID { get; set; }
        public string Day7SwitchProfileID { get; set; }
        public string Day8SwitchProfileID { get; set; }
        public string Day9SwitchProfileID { get; set; }
        public string Day10SwitchProfileID { get; set; }
        public string Day11SwitchProfileID { get; set; }
        public string Day12SwitchProfileID { get; set; }
        public string Day13SwitchProfileID { get; set; }
        public string Day14SwitchProfileID { get; set; }
        public string Day15SwitchProfileID { get; set; }
        public string Day16SwitchProfileID { get; set; }
        public string Day17SwitchProfileID { get; set; }
        public string Day18SwitchProfileID { get; set; }
        public string Day19SwitchProfileID { get; set; }
        public string Day20SwitchProfileID { get; set; }
        public string Day21SwitchProfileID { get; set; }
        public string Day22SwitchProfileID { get; set; }
        public string Day23SwitchProfileID { get; set; }
        public string Day24SwitchProfileID { get; set; }
        public string Day25SwitchProfileID { get; set; }
        public string Day26SwitchProfileID { get; set; }
        public string Day27SwitchProfileID { get; set; }
        public string Day28SwitchProfileID { get; set; }
        public string Day29SwitchProfileID { get; set; }
        public string Day30SwitchProfileID { get; set; }
        public string Day31SwitchProfileID { get; set; }
    }
}
