//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShiftResource
    {
        public ShiftResource()
        {
            this.ResourceEvents = new HashSet<ResourceEvent>();
            this.ResourceEventMappeds = new HashSet<ResourceEventMapped>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public bool IsDefaultLoaded { get; set; }
        public string Color { get; set; }
        public int OrderCase { get; set; }
    
        public virtual ICollection<ResourceEvent> ResourceEvents { get; set; }
        public virtual ICollection<ResourceEventMapped> ResourceEventMappeds { get; set; }
    }
}
