//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shift_Breaks
    {
        public int ID { get; set; }
        public int Shift_ID { get; set; }
        public long Break_ID { get; set; }
        public Nullable<System.DateTime> TimeFrom { get; set; }
        public Nullable<System.DateTime> TimeTo { get; set; }
    
        public virtual Break Break { get; set; }
        public virtual DP_Shifts DP_Shifts { get; set; }
    }
}
