//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurchargesAccountsMapping
    {
        public long ID { get; set; }
        public long SurchargeID { get; set; }
        public long AccountID { get; set; }
        public bool Active { get; set; }
        public int AccountPosition { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Surcharge Surcharge { get; set; }
    }
}
