//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Surcharge
    {
        public Surcharge()
        {
            this.SurchargesAccountsMappings = new HashSet<SurchargesAccountsMapping>();
        }
    
        public long ID { get; set; }
        public long Surchage_Nr { get; set; }
        public string Name { get; set; }
        public string SurchargeFactor { get; set; }
        public Nullable<System.DateTime> TimeFrom { get; set; }
        public Nullable<System.DateTime> TimeTo { get; set; }
        public Nullable<System.DateTime> DurationFrom { get; set; }
        public Nullable<System.DateTime> DurationTo { get; set; }
        public Nullable<System.DateTime> ExtraDurationFrom { get; set; }
        public Nullable<System.DateTime> ExtraDurationTo { get; set; }
        public string Memo { get; set; }
        public Nullable<long> WeekDays_ID { get; set; }
    
        public virtual SurchargeDay SurchargeDay { get; set; }
        public virtual ICollection<SurchargesAccountsMapping> SurchargesAccountsMappings { get; set; }
    }
}
