//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurchargeDay
    {
        public SurchargeDay()
        {
            this.Surcharges = new HashSet<Surcharge>();
        }
    
        public long ID { get; set; }
        public Nullable<bool> Mon { get; set; }
        public Nullable<bool> Tue { get; set; }
        public Nullable<bool> Wed { get; set; }
        public Nullable<bool> Thur { get; set; }
        public Nullable<bool> Fri { get; set; }
        public Nullable<bool> Sat { get; set; }
        public Nullable<bool> Sun { get; set; }
        public Nullable<bool> Holiday { get; set; }
    
        public virtual ICollection<Surcharge> Surcharges { get; set; }
    }
}
