//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurchargeMapped
    {
        public SurchargeMapped()
        {
            this.Tariffs = new HashSet<Tariff>();
        }
    
        public int ID { get; set; }
        public int Surchage_Nr { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> TimeFrom { get; set; }
        public Nullable<System.DateTime> TimeTo { get; set; }
        public string Memo { get; set; }
    
        public virtual ICollection<Tariff> Tariffs { get; set; }
    }
}
