//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SwitchProfile
    {
        public long ID { get; set; }
        public long Profile_Nr { get; set; }
        public string Profile_Id { get; set; }
        public string Description { get; set; }
        public Nullable<int> ProfileTimeMode { get; set; }
        public string Memo { get; set; }
    }
}
