//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SwitchCalendarMapped
    {
        public SwitchCalendarMapped()
        {
            this.SwitchCalendarMonthMappeds = new HashSet<SwitchCalendarMonthMapped>();
        }
    
        public long Id { get; set; }
        public int CalendarYear { get; set; }
        public string SwitchCalendarNumber { get; set; }
        public string SwitchCalendarName { get; set; }
        public string Memo { get; set; }
    
        public virtual ICollection<SwitchCalendarMonthMapped> SwitchCalendarMonthMappeds { get; set; }
    }
}
