//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SwitchPlan
    {
        public long Id { get; set; }
        public long SwitchPlanNumber { get; set; }
        public string SwitchPlanName { get; set; }
        public Nullable<long> SwitchCalendarId { get; set; }
        public Nullable<long> BuidingPlanID { get; set; }
        public Nullable<long> HolidayPlanCalendarId { get; set; }
    
        public virtual BuildingPlan BuildingPlan { get; set; }
        public virtual HolidayPlanCalendar HolidayPlanCalendar { get; set; }
        public virtual SwitchCalendar SwitchCalendar { get; set; }
    }
}
