//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SwitchCalendar
    {
        public SwitchCalendar()
        {
            this.SwitchCalendarMonths = new HashSet<SwitchCalendarMonth>();
            this.SwitchPlans = new HashSet<SwitchPlan>();
        }
    
        public long Id { get; set; }
        public int CalendarYear { get; set; }
        public string SwitchCalendarNumber { get; set; }
        public string SwitchCalendarName { get; set; }
        public string Memo { get; set; }
    
        public virtual ICollection<SwitchCalendarMonth> SwitchCalendarMonths { get; set; }
        public virtual ICollection<SwitchPlan> SwitchPlans { get; set; }
    }
}
