//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TA_BookingsReport
    {
        public TA_BookingsReport()
        {
            this.TA_BookingsReportAbsences = new HashSet<TA_BookingsReportAbsences>();
            this.TA_BookingsReportAccounts = new HashSet<TA_BookingsReportAccounts>();
            this.TA_BookingsReportTitles = new HashSet<TA_BookingsReportTitles>();
        }
    
        public int ID { get; set; }
        public int Number { get; set; }
        public string Name { get; set; }
        public int BookingsReportTypeNr { get; set; }
        public int DailyBookingsTabPosition { get; set; }
        public int Orientation { get; set; }
        public int AbsencePosition { get; set; }
        public int TpPosition { get; set; }
        public int ShiftPosition { get; set; }
    
        public virtual ICollection<TA_BookingsReportAbsences> TA_BookingsReportAbsences { get; set; }
        public virtual ICollection<TA_BookingsReportAccounts> TA_BookingsReportAccounts { get; set; }
        public virtual ICollection<TA_BookingsReportTitles> TA_BookingsReportTitles { get; set; }
    }
}
