//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TA_BookingsReportTypes
    {
        public int ID { get; set; }
        public int Number { get; set; }
        public string Name { get; set; }
        public int InBookings { get; set; }
        public int OutBookings { get; set; }
    }
}
