//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TA_TerminalGroupMapping
    {
        public long ID { get; set; }
        public Nullable<long> TerminalGroupId { get; set; }
        public Nullable<long> TerminalInstanceId { get; set; }
        public Nullable<long> Pers_Nr { get; set; }
    
        public virtual TA_TerminalGroups TA_TerminalGroups { get; set; }
        public virtual TerminalConfig TerminalConfig { get; set; }
    }
}
