//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tariff
    {
        public Tariff()
        {
            this.EmployeeTariffs = new HashSet<EmployeeTariff>();
            this.PersonnelTariffs = new HashSet<PersonnelTariff>();
            this.TariffCalendars = new HashSet<TariffCalendar>();
        }
    
        public long Id { get; set; }
        public int TariffNumber { get; set; }
        public string TariffIdNumber { get; set; }
        public string TariffName { get; set; }
        public System.DateTime ValidFrom { get; set; }
        public System.DateTime ValidTo { get; set; }
        public string Memo { get; set; }
        public Nullable<long> MapCalendarId { get; set; }
        public Nullable<long> PlannedCalendarId { get; set; }
        public Nullable<int> SurchargeId { get; set; }
    
        public virtual ICollection<EmployeeTariff> EmployeeTariffs { get; set; }
        public virtual MapCalendarMapped MapCalendarMapped { get; set; }
        public virtual ICollection<PersonnelTariff> PersonnelTariffs { get; set; }
        public virtual PlannedCalendarMapped PlannedCalendarMapped { get; set; }
        public virtual SurchargeMapped SurchargeMapped { get; set; }
        public virtual ICollection<TariffCalendar> TariffCalendars { get; set; }
    }
}
