//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbAccessPlanGroup
    {
        public TbAccessPlanGroup()
        {
            this.AccessPlanGroupDoorMappings = new HashSet<AccessPlanGroupDoorMapping>();
            this.MemberAccessGroups = new HashSet<MemberAccessGroup>();
            this.Pers_AccessGroups = new HashSet<Pers_AccessGroups>();
        }
    
        public long ID { get; set; }
        public long AccessPlanGroupNr { get; set; }
        public string AccessPlanGroupName { get; set; }
        public Nullable<long> BuildingPlanID { get; set; }
        public Nullable<long> AccessCalendarId { get; set; }
        public Nullable<long> HolidayPlanCalendarId { get; set; }
    
        public virtual AccessCalendar AccessCalendar { get; set; }
        public virtual ICollection<AccessPlanGroupDoorMapping> AccessPlanGroupDoorMappings { get; set; }
        public virtual BuildingPlan BuildingPlan { get; set; }
        public virtual HolidayPlanCalendar HolidayPlanCalendar { get; set; }
        public virtual ICollection<MemberAccessGroup> MemberAccessGroups { get; set; }
        public virtual ICollection<Pers_AccessGroups> Pers_AccessGroups { get; set; }
    }
}
