//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbAccessPlan
    {
        public TbAccessPlan()
        {
            this.MembersAccessPlanMappings = new HashSet<MembersAccessPlanMapping>();
            this.ReaderAccessPlans = new HashSet<ReaderAccessPlan>();
            this.TbAccessPlanMembersMappings = new HashSet<TbAccessPlanMembersMapping>();
            this.TbAccessPlanPersMappings = new HashSet<TbAccessPlanPersMapping>();
        }
    
        public long ID { get; set; }
        public long AccessPlanNr { get; set; }
        public string AccessPlanDescription { get; set; }
        public long AccessGroupID { get; set; }
        public Nullable<long> AccessCalendarId { get; set; }
        public Nullable<long> BuildingPlanID { get; set; }
        public Nullable<long> HolidayPlanCalendarId { get; set; }
    
        public virtual AccessGroup AccessGroup { get; set; }
        public virtual BuildingPlan BuildingPlan { get; set; }
        public virtual HolidayPlanCalendar HolidayPlanCalendar { get; set; }
        public virtual ICollection<MembersAccessPlanMapping> MembersAccessPlanMappings { get; set; }
        public virtual ICollection<ReaderAccessPlan> ReaderAccessPlans { get; set; }
        public virtual ICollection<TbAccessPlanMembersMapping> TbAccessPlanMembersMappings { get; set; }
        public virtual ICollection<TbAccessPlanPersMapping> TbAccessPlanPersMappings { get; set; }
    }
}
