//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbVisitorPlan
    {
        public TbVisitorPlan()
        {
            this.ReaderVisitorPlans = new HashSet<ReaderVisitorPlan>();
            this.VisitorAccessTimes = new HashSet<VisitorAccessTime>();
        }
    
        public long ID { get; set; }
        public long VisitorPlanNr { get; set; }
        public string VisitorPlanDescription { get; set; }
        public Nullable<long> AccessCalendarId { get; set; }
        public Nullable<long> BuildingPlanID { get; set; }
        public Nullable<long> HolidayPlanCalendarId { get; set; }
    
        public virtual AccessCalendar AccessCalendar { get; set; }
        public virtual BuildingPlan BuildingPlan { get; set; }
        public virtual HolidayPlanCalendar HolidayPlanCalendar { get; set; }
        public virtual ICollection<ReaderVisitorPlan> ReaderVisitorPlans { get; set; }
        public virtual ICollection<VisitorAccessTime> VisitorAccessTimes { get; set; }
    }
}
