//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TerminalOEM
    {
        public TerminalOEM()
        {
            this.TerminalConfigs = new HashSet<TerminalConfig>();
            this.Terminals = new HashSet<Terminal>();
        }
    
        public int ID { get; set; }
        public Nullable<int> TermOEMId { get; set; }
        public string TermOEMDesc { get; set; }
    
        public virtual ICollection<TerminalConfig> TerminalConfigs { get; set; }
        public virtual ICollection<Terminal> Terminals { get; set; }
    }
}
