//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TerminalInfoText
    {
        public long ID { get; set; }
        public long TerminalConfigID { get; set; }
        public Nullable<int> InfoTextNr { get; set; }
        public string InfoText { get; set; }
    
        public virtual TerminalConfig TerminalConfig { get; set; }
    }
}
