//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TerminalsNew
    {
        public long ID { get; set; }
        public Nullable<long> TermOEMID { get; set; }
        public string TermType { get; set; }
        public string Description { get; set; }
        public string Connection { get; set; }
        public string Reader { get; set; }
        public string Access { get; set; }
        public string Image { get; set; }
        public string TermOEM { get; set; }
    }
}
