//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TerminalConnect
    {
        public TerminalConnect()
        {
            this.TerminalConfigs = new HashSet<TerminalConfig>();
        }
    
        public int ID { get; set; }
        public string Connection { get; set; }
        public string IPAddress { get; set; }
        public string IPPort { get; set; }
        public bool ActiveTerminal { get; set; }
        public bool PersnoPIN { get; set; }
        public bool FPRead { get; set; }
        public bool APPosting { get; set; }
        public bool TAPPosting { get; set; }
        public string SerialNumber { get; set; }
    
        public virtual ICollection<TerminalConfig> TerminalConfigs { get; set; }
    }
}
