//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TerminalDatafoxFunction
    {
        public long ID { get; set; }
        public long TerminalID { get; set; }
        public int BookingSpan { get; set; }
        public Nullable<bool> AccessControl { get; set; }
        public Nullable<bool> Project { get; set; }
        public Nullable<bool> ReaderList { get; set; }
        public Nullable<bool> ActionList { get; set; }
        public Nullable<bool> TimeList { get; set; }
        public Nullable<bool> LocationList { get; set; }
        public Nullable<bool> HolidayList { get; set; }
        public Nullable<bool> IdentificationList { get; set; }
        public Nullable<bool> EventList { get; set; }
    
        public virtual TerminalConfig TerminalConfig { get; set; }
    }
}
