//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TerminalInfo
    {
        public TerminalInfo()
        {
            this.TerminalConfigs = new HashSet<TerminalConfig>();
        }
    
        public int ID { get; set; }
        public string InfoText1 { get; set; }
        public string InfoText2 { get; set; }
        public string InfoText3 { get; set; }
        public string InfoText4 { get; set; }
        public string Functionkey1 { get; set; }
        public string Functionkey2 { get; set; }
        public string Functionkey3 { get; set; }
        public string Functionkey4 { get; set; }
        public string Functionkey5 { get; set; }
        public string Functionkey6 { get; set; }
        public string Functionkey7 { get; set; }
        public string Functionkey8 { get; set; }
        public string DoorAssign { get; set; }
        public string Memo { get; set; }
    
        public virtual ICollection<TerminalConfig> TerminalConfigs { get; set; }
    }
}
