//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TerminalConfig
    {
        public TerminalConfig()
        {
            this.TA_TerminalGroupMapping = new HashSet<TA_TerminalGroupMapping>();
            this.TerminalDatafoxFunctions = new HashSet<TerminalDatafoxFunction>();
            this.TerminalFunctionKeys = new HashSet<TerminalFunctionKey>();
            this.TerminalGroupMappings = new HashSet<TerminalGroupMapping>();
            this.TerminalInfoTexts = new HashSet<TerminalInfoText>();
            this.TerminalReaders = new HashSet<TerminalReader>();
            this.TerminalUtilities = new HashSet<TerminalUtility>();
        }
    
        public long ID { get; set; }
        public int TermID { get; set; }
        public string TermType { get; set; }
        public string Description { get; set; }
        public Nullable<int> TerminalConnectId { get; set; }
        public Nullable<int> TerminalInfoId { get; set; }
        public Nullable<int> TerminalOEMId { get; set; }
        public string Status { get; set; }
        public bool IsActive { get; set; }
        public string SerialNumber { get; set; }
        public string ConnectionType { get; set; }
        public string IpAddress { get; set; }
        public Nullable<int> Port { get; set; }
        public string Memo { get; set; }
        public Nullable<int> TerminalId { get; set; }
        public Nullable<int> ZkRelayTime { get; set; }
        public Nullable<int> ZkExternalReaders { get; set; }
    
        public virtual ICollection<TA_TerminalGroupMapping> TA_TerminalGroupMapping { get; set; }
        public virtual TerminalConnect TerminalConnect { get; set; }
        public virtual TerminalInfo TerminalInfo { get; set; }
        public virtual TerminalOEM TerminalOEM { get; set; }
        public virtual Terminal Terminal { get; set; }
        public virtual ICollection<TerminalDatafoxFunction> TerminalDatafoxFunctions { get; set; }
        public virtual ICollection<TerminalFunctionKey> TerminalFunctionKeys { get; set; }
        public virtual ICollection<TerminalGroupMapping> TerminalGroupMappings { get; set; }
        public virtual ICollection<TerminalInfoText> TerminalInfoTexts { get; set; }
        public virtual ICollection<TerminalReader> TerminalReaders { get; set; }
        public virtual ICollection<TerminalUtility> TerminalUtilities { get; set; }
    }
}
