//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TerminalGroup
    {
        public TerminalGroup()
        {
            this.TerminalGroupMappings = new HashSet<TerminalGroupMapping>();
        }
    
        public long ID { get; set; }
        public long GroupNr { get; set; }
        public string GroupDescription { get; set; }
    
        public virtual ICollection<TerminalGroupMapping> TerminalGroupMappings { get; set; }
    }
}
