//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Terminal
    {
        public Terminal()
        {
            this.TerminalConfigs = new HashSet<TerminalConfig>();
        }
    
        public int ID { get; set; }
        public string TermType { get; set; }
        public string Description { get; set; }
        public string Connection { get; set; }
        public string Reader { get; set; }
        public string Access { get; set; }
        public string Image { get; set; }
        public string TermOEM { get; set; }
        public Nullable<int> TermOEMID { get; set; }
        public string TerminalPage { get; set; }
    
        public virtual ICollection<TerminalConfig> TerminalConfigs { get; set; }
        public virtual TerminalOEM TerminalOEM { get; set; }
    }
}
