//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TerminalReadersStatic
    {
        public TerminalReadersStatic()
        {
            this.TerminalReaders = new HashSet<TerminalReader>();
        }
    
        public int ID { get; set; }
        public string ReaderType { get; set; }
        public string Description { get; set; }
        public string Installation { get; set; }
        public string Image { get; set; }
        public Nullable<int> ReaderIdentifier { get; set; }
    
        public virtual ICollection<TerminalReader> TerminalReaders { get; set; }
    }
}
