//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_ERPSoftwareUpdateService
    {
        public long ID { get; set; }
        public Nullable<System.DateTime> InstallationDate { get; set; }
        public string PurchaseVersion { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public string LastVersionAfterUpdate { get; set; }
        public Nullable<System.DateTime> UpdateAfterBuying { get; set; }
        public Nullable<bool> SoftwareUpdateContract { get; set; }
        public Nullable<System.DateTime> SoftwareContractFrom { get; set; }
        public Nullable<System.DateTime> EndOfContract { get; set; }
        public Nullable<bool> UpdateInfoByMail { get; set; }
        public string ModuleName { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public long ModuleNumber { get; set; }
        public Nullable<int> ContractStatusNr { get; set; }
    }
}
