//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_TerminalReader
    {
        public long TerminalID { get; set; }
        public int TermID { get; set; }
        public string TermType { get; set; }
        public string TerminalDescription { get; set; }
        public Nullable<int> Direction { get; set; }
        public long ReaderId { get; set; }
        public bool ReaderAssigned { get; set; }
        public Nullable<int> Status { get; set; }
        public string ReaderInfo { get; set; }
        public int ReaderNo { get; set; }
        public long ID { get; set; }
        public string unique_id { get; set; }
        public bool ReaderStatus { get; set; }
        public bool AccessProfileActive { get; set; }
        public bool SwitchProfileActive { get; set; }
        public bool ManualOpeningActive { get; set; }
        public long BuildingPlanID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<int> BuildingID { get; set; }
        public Nullable<int> FloorID { get; set; }
        public Nullable<int> RoomID { get; set; }
        public Nullable<int> DoorID { get; set; }
        public Nullable<int> TerminalTypeID { get; set; }
        public string IpAddress { get; set; }
        public Nullable<int> Port { get; set; }
        public string ConnectionType { get; set; }
        public Nullable<int> PassBackNr { get; set; }
        public Nullable<int> Lock { get; set; }
        public string ReaderDescription { get; set; }
        public string ReaderType { get; set; }
        public bool TA_Come { get; set; }
        public bool TA_Go { get; set; }
    }
}
