//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_DFHoliday
    {
        public string HolidayDate { get; set; }
        public long RefGroup { get; set; }
        public int RefTime { get; set; }
        public string TerminalDescription { get; set; }
    }
}
