//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_AccessLogs
    {
        public Nullable<long> ID { get; set; }
        public int Pers_Type { get; set; }
        public long ID_Nr { get; set; }
        public long Card_Nr { get; set; }
        public string FullName { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string ClientName { get; set; }
        public Nullable<System.DateTime> AccessEndData { get; set; }
        public int TA_Come { get; set; }
        public int TA_Go { get; set; }
        public System.DateTime BookingTime { get; set; }
        public int BookingCorrection { get; set; }
        public string DynamicField1 { get; set; }
        public long LogID { get; set; }
        public string PlanDefinition { get; set; }
        public Nullable<long> BuildingPlanID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<int> BuildingID { get; set; }
        public Nullable<int> FloorID { get; set; }
        public Nullable<int> RoomID { get; set; }
        public Nullable<int> DoorID { get; set; }
    }
}
