//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_CardAllocationOverview
    {
        public Nullable<long> ID { get; set; }
        public long Pers_Nr { get; set; }
        public bool PersonnelActive { get; set; }
        public string ClientName { get; set; }
        public long ClientID { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string FullName { get; set; }
        public string LocationName { get; set; }
        public Nullable<long> LocationID { get; set; }
        public string DepartmentName { get; set; }
        public Nullable<long> DepartmentID { get; set; }
        public string CostCenterName { get; set; }
        public Nullable<long> CostCenterID { get; set; }
        public long TransPonderID { get; set; }
        public long TransponderNr { get; set; }
        public Nullable<int> Action { get; set; }
        public Nullable<bool> TransponderStatus { get; set; }
        public Nullable<System.DateTime> ValidTo { get; set; }
        public Nullable<System.DateTime> TransponderDeactivatedOn { get; set; }
    }
}
