//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_TerminalHolidays
    {
        public string TerminalSerialNumber { get; set; }
        public string TerminalDescription { get; set; }
        public System.DateTime HolidayDate { get; set; }
        public long AccessProfileID { get; set; }
    }
}
