//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VirtualTerminal
    {
        public long ID { get; set; }
        public long TerminalId { get; set; }
        public string Description { get; set; }
        public int LocationId { get; set; }
        public int CostCenterId { get; set; }
        public Nullable<bool> TerminalActive { get; set; }
        public Nullable<int> TerminalType { get; set; }
        public Nullable<int> LogoutCode { get; set; }
        public Nullable<bool> RealTimeActive { get; set; }
        public string TerminalCostCenter { get; set; }
        public bool DisplayDepartment { get; set; }
        public bool DisplayPersonalNumber { get; set; }
        public bool DisplayCostCenter { get; set; }
        public int FunctionKeysDisplayMode { get; set; }
        public Nullable<bool> TerminalOffline { get; set; }
        public string DatabaseServer { get; set; }
        public Nullable<int> DataIntervalHours { get; set; }
        public Nullable<int> DataintervalMinutes { get; set; }
    }
}
