//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VirtualTerminalInputSetting
    {
        public long ID { get; set; }
        public Nullable<long> TerminalID { get; set; }
        public bool Biometric { get; set; }
        public bool RFID { get; set; }
        public bool BarCode { get; set; }
        public bool PinCode { get; set; }
        public bool PersonalNumber { get; set; }
        public bool InividualNumber { get; set; }
    }
}
