//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VirtualTerminalCommunicationSetting
    {
        public int ID { get; set; }
        public string FixedIPAddress { get; set; }
        public Nullable<bool> FixedIPAddressEnabled { get; set; }
        public Nullable<int> FixedIPAddressPort { get; set; }
        public string DynamicIPAddress { get; set; }
        public Nullable<bool> DynamicIPAddressEnabled { get; set; }
        public Nullable<int> DynamicIPAddressPort { get; set; }
        public Nullable<bool> Active { get; set; }
        public long TerminalId { get; set; }
    }
}
