//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisitorApplication
    {
        public VisitorApplication()
        {
            this.VisitorAdditionalInfoes = new HashSet<VisitorAdditionalInfo>();
            this.VisitorContacts = new HashSet<VisitorContact>();
        }
    
        public long ID { get; set; }
        public long ApplicationID { get; set; }
        public long VisitorNr { get; set; }
        public long PersonalID { get; set; }
        public string VisitorName { get; set; }
        public string Title { get; set; }
        public string IdentificationNr { get; set; }
        public string PassportNr { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<System.DateTime> DateFiled { get; set; }
        public Nullable<System.DateTime> TimeFiled { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<System.DateTime> EntryTime { get; set; }
        public Nullable<System.DateTime> ExitDate { get; set; }
        public Nullable<System.DateTime> ExitTime { get; set; }
        public string Nationality { get; set; }
        public bool Active { get; set; }
        public Nullable<long> VisitorType { get; set; }
        public string Memo { get; set; }
    
        public virtual ICollection<VisitorAdditionalInfo> VisitorAdditionalInfoes { get; set; }
        public virtual ICollection<VisitorContact> VisitorContacts { get; set; }
    }
}
