//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visitor
    {
        public Visitor()
        {
            this.VisitorAccessTimes = new HashSet<VisitorAccessTime>();
            this.VisitorTransponders = new HashSet<VisitorTransponder>();
        }
    
        public long ID { get; set; }
        public long VisitorID { get; set; }
        public Nullable<long> PersonalID { get; set; }
        public string SurName { get; set; }
        public string Fullname { get; set; }
        public Nullable<long> Company { get; set; }
        public string Street { get; set; }
        public string VisitorNr { get; set; }
        public string Location { get; set; }
        public string Telephone { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string PostalCode { get; set; }
        public Nullable<int> VisitorType { get; set; }
        public string StreetNr { get; set; }
        public Nullable<System.DateTime> DateActivated { get; set; }
        public Nullable<long> PersNr { get; set; }
        public Nullable<int> CompanyTo { get; set; }
        public string VisitorPhoto { get; set; }
        public Nullable<bool> CardActive { get; set; }
        public string VehicleRegNr { get; set; }
        public Nullable<long> VisitorVehicleType { get; set; }
        public string VisitReason { get; set; }
    
        public virtual Personal Personal { get; set; }
        public virtual VehicleType VehicleType { get; set; }
        public virtual ICollection<VisitorAccessTime> VisitorAccessTimes { get; set; }
        public virtual VisitorCompanyTb VisitorCompanyTb { get; set; }
        public virtual ICollection<VisitorTransponder> VisitorTransponders { get; set; }
    }
}
