//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisitorAdditionalInfo
    {
        public long ID { get; set; }
        public long VisitorID { get; set; }
        public string PhysicalAddress { get; set; }
        public string Street { get; set; }
        public string PlaceOfBirth { get; set; }
        public string MaritalStatus { get; set; }
        public string Profession { get; set; }
        public string VehicleModel { get; set; }
        public string VehicleReg { get; set; }
    
        public virtual VisitorApplication VisitorApplication { get; set; }
    }
}
