//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisitorAccessTime
    {
        public long ID { get; set; }
        public long VisitorId { get; set; }
        public long VisitInstanceId { get; set; }
        public string CardNr { get; set; }
        public string PinCode { get; set; }
        public Nullable<long> VisitPlanId { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> AutoEndDate { get; set; }
        public string AutoEndDateStd { get; set; }
        public string Memo { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public Nullable<bool> AccessPlanActive { get; set; }
        public Nullable<System.DateTime> VisitAccessStartDate { get; set; }
        public Nullable<System.DateTime> VisitAccessEndDate { get; set; }
        public string VisitReason { get; set; }
        public Nullable<System.DateTime> DateActivated { get; set; }
        public Nullable<long> PersNr { get; set; }
        public Nullable<long> CompanyTo { get; set; }
        public Nullable<bool> IsCanceled { get; set; }
        public Nullable<bool> AutoLogout { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual TbVisitorPlan TbVisitorPlan { get; set; }
        public virtual Visitor Visitor { get; set; }
    }
}
