//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisitorPlanGroup
    {
        public long Id { get; set; }
        public int AccessGroupNumber { get; set; }
        public string AccessGroupName { get; set; }
        public int AccessGroupType { get; set; }
        public string Memo { get; set; }
    }
}
