//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisitorContact
    {
        public long ID { get; set; }
        public long VisitorID { get; set; }
        public string Company { get; set; }
        public string CompanyTel { get; set; }
        public string PrivateTel { get; set; }
        public string CompanyMobile { get; set; }
        public string PrivateMobile { get; set; }
        public string CompanyFax { get; set; }
        public string PrivateFax { get; set; }
        public string CompanyEmail { get; set; }
        public string PrivateEmail { get; set; }
        public string PostalAddress { get; set; }
        public string PostalCode { get; set; }
        public string ZipCode { get; set; }
        public string Zip { get; set; }
    
        public virtual VisitorApplication VisitorApplication { get; set; }
    }
}
