//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwPersDataZUT
    {
        public long ID { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string FullName { get; set; }
        public string Title { get; set; }
        public System.DateTime EntryDate { get; set; }
        public Nullable<System.DateTime> ExitDate { get; set; }
        public bool Active { get; set; }
        public Nullable<long> PersType { get; set; }
        public string Memo { get; set; }
        public long Expr4 { get; set; }
        public Nullable<long> Card_Nr { get; set; }
        public bool CardActive { get; set; }
        public Nullable<bool> Imported { get; set; }
        public long AccessPlanID { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string Passport_Nr { get; set; }
        public string PhysicalAddress { get; set; }
        public string Street { get; set; }
        public string PlaceOfBirth { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Gender { get; set; }
        public string MaritalStatus { get; set; }
        public string Position { get; set; }
        public string Profession { get; set; }
        public string Nationality { get; set; }
        public string VehicleModel { get; set; }
        public string VehicleReg { get; set; }
        public string CompanyName { get; set; }
        public string CompanyTel { get; set; }
        public string PrivateTel { get; set; }
        public string CompanyMobile { get; set; }
        public string PrivateMobile { get; set; }
        public string CompanyFax { get; set; }
        public string PrivateFax { get; set; }
        public string CompanyEmail { get; set; }
        public string PrivateEmail { get; set; }
        public string PostalAddress { get; set; }
        public string PostalCode { get; set; }
        public long DepartmentID { get; set; }
        public long VisitorID { get; set; }
        public long PinCode { get; set; }
        public int PinCodeType { get; set; }
        public bool PinCodeStatus { get; set; }
        public long CostCenterID { get; set; }
        public Nullable<long> VehicleID { get; set; }
    }
}
