//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwPersPinCode
    {
        public long Pers_Nr { get; set; }
        public Nullable<int> Aus_PinCodeType { get; set; }
        public string Aus_PinCode { get; set; }
        public Nullable<bool> Aus_PinCodeStatus { get; set; }
        public Nullable<int> Nur_PinCodeType { get; set; }
        public string Nur_PinCode { get; set; }
        public Nullable<bool> Nur_PinCodeStatus { get; set; }
        public Nullable<int> Sicher_PinCodeType { get; set; }
        public string Scher_PinCode { get; set; }
        public Nullable<bool> Scher_PinCodeStatus { get; set; }
    }
}
