//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwPersonnelData
    {
        public long ID { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string FullName { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<System.DateTime> ExitDate { get; set; }
        public bool Active { get; set; }
        public Nullable<long> PersType { get; set; }
        public string Memo { get; set; }
        public long Pers_Nr { get; set; }
        public bool CardActive { get; set; }
        public bool Imported { get; set; }
        public string Passport_Nr { get; set; }
        public string PhysicalAddress { get; set; }
        public string Street { get; set; }
        public string PlaceOfBirth { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Gender { get; set; }
        public string MaritalStatus { get; set; }
        public string Position { get; set; }
        public string Profession { get; set; }
        public string Nationality { get; set; }
        public string VehicleModel { get; set; }
        public string VehicleReg { get; set; }
        public string CompanyName { get; set; }
        public string CompanyTel { get; set; }
        public string PrivateTel { get; set; }
        public string CompanyMobile { get; set; }
        public string PrivateMobile { get; set; }
        public string CompanyFax { get; set; }
        public string PrivateFax { get; set; }
        public string CompanyEmail { get; set; }
        public string PrivateEmail { get; set; }
        public string PostalAddress { get; set; }
        public string PostalCode { get; set; }
        public Nullable<long> DepartmentID { get; set; }
        public Nullable<long> CostCenterID { get; set; }
        public Nullable<long> VehicleID { get; set; }
        public Nullable<long> LocationID { get; set; }
        public string LocationName { get; set; }
        public string DepartmentName { get; set; }
        public string CostCenterName { get; set; }
        public long PersonnelNr_string { get; set; }
        public Nullable<long> IdentificationNr_string { get; set; }
        public string PersNr_Fullname { get; set; }
        public string EyeColor { get; set; }
        public string Height { get; set; }
        public string Expr1 { get; set; }
        public string Salutation { get; set; }
        public string Additonal { get; set; }
        public Nullable<System.DateTime> Since { get; set; }
        public string Bankname { get; set; }
        public string AccountOwner { get; set; }
        public string BankCode { get; set; }
        public string AccountNo { get; set; }
        public string BIC { get; set; }
        public string IBAN { get; set; }
        public string DriversLicense { get; set; }
        public string Children { get; set; }
        public string TaxOfficee { get; set; }
        public string TaxClass { get; set; }
        public string HealthInsuarance { get; set; }
        public string HealInsuaranceNo { get; set; }
        public string PensionInsuarance { get; set; }
        public string SozVerzNo { get; set; }
        public string Contract { get; set; }
        public Nullable<System.DateTime> EmployedFrom { get; set; }
        public string LearnedOccupation { get; set; }
        public string EmployedAs { get; set; }
        public string EmploymentType { get; set; }
        public string ResidencePermit { get; set; }
        public string AuthorisedBy { get; set; }
        public string ApprovedBy { get; set; }
        public string NoOfHours { get; set; }
        public Nullable<System.DateTime> EndOfContract { get; set; }
        public Nullable<System.DateTime> EliminatedOn { get; set; }
        public string Reason { get; set; }
        public string CertificateOfEmployment { get; set; }
        public Nullable<long> ClientID { get; set; }
        public string ClientName { get; set; }
        public string StreetNr { get; set; }
        public string Expr2 { get; set; }
        public string Pers_Passport { get; set; }
        public Nullable<int> ActiveCardType { get; set; }
        public Nullable<long> Card_Nr { get; set; }
        public string DynamicField1 { get; set; }
        public Nullable<long> Client_Nr { get; set; }
    }
}
