//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwVisitorCompany
    {
        public long ID { get; set; }
        public long VisitorID { get; set; }
        public Nullable<long> PersonalID { get; set; }
        public string SurName { get; set; }
        public string FullName { get; set; }
        public string Company { get; set; }
        public string CompanyStreet { get; set; }
        public string CompanyStreetNr { get; set; }
        public string CompanyPostalCode { get; set; }
        public string Street { get; set; }
        public string VisitorNr { get; set; }
        public string Location { get; set; }
        public string Telephone { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string PostalCode { get; set; }
        public Nullable<int> VisitorType { get; set; }
        public string StreetNr { get; set; }
        public string VisitorPhoto { get; set; }
        public Nullable<bool> CardActive { get; set; }
        public string VehicleRegNr { get; set; }
        public Nullable<long> VisitorVehicleType { get; set; }
        public string VisitReason { get; set; }
    }
}
