//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkedHoursAcc
    {
        public int ID { get; set; }
        public long AccountID { get; set; }
        public System.DateTime Date { get; set; }
        public decimal HoursWorked { get; set; }
        public string Account { get; set; }
        public int EmpID { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
