//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZITERM_V20_Vorlauftasten
    {
        public Nullable<int> V_Nr { get; set; }
        public string V_Funk { get; set; }
        public string V_Bezeichnung { get; set; }
        public Nullable<int> V_K_nr { get; set; }
        public string V_Abw_nr { get; set; }
        public Nullable<bool> V_Grenzbuch { get; set; }
        public Nullable<bool> V_AbSofort { get; set; }
        public Nullable<bool> V_Fortschreiben { get; set; }
        public Nullable<bool> V_Pausen { get; set; }
        public int ID { get; set; }
        public Nullable<bool> V_NOISTVERR { get; set; }
        public Nullable<bool> V_SollAZ { get; set; }
        public Nullable<bool> V_WertungEnd { get; set; }
        public Nullable<bool> V_Tarif { get; set; }
        public Nullable<bool> V_StartRegelarbeitszeit { get; set; }
        public Nullable<bool> V_StartWertungsrahmen { get; set; }
        public Nullable<bool> V_BeginnSollzeit { get; set; }
        public Nullable<bool> V_KeineEinbuchung { get; set; }
        public Nullable<bool> V_NichtAnTerminalSenden { get; set; }
    }
}
