//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZuttritProfilesTimeFrame
    {
        public long ID { get; set; }
        public Nullable<long> AccessProfID { get; set; }
        public bool ProfilAktiv { get; set; }
        public int Level { get; set; }
        public System.DateTime MonFrom { get; set; }
        public System.DateTime MonTo { get; set; }
        public System.DateTime TueFrom { get; set; }
        public System.DateTime TueTo { get; set; }
        public System.DateTime WedFrom { get; set; }
        public System.DateTime WedTo { get; set; }
        public System.DateTime ThurFrom { get; set; }
        public System.DateTime ThurTo { get; set; }
        public System.DateTime FriFrom { get; set; }
        public System.DateTime FriTo { get; set; }
        public System.DateTime SatFrom { get; set; }
        public System.DateTime SatTo { get; set; }
        public System.DateTime SunFrom { get; set; }
        public System.DateTime SunTo { get; set; }
    
        public virtual ZuttritProfile ZuttritProfile { get; set; }
    }
}
