//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruAll.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZuttritProfile
    {
        public ZuttritProfile()
        {
            this.AccessProfileAccessGroupMappings = new HashSet<AccessProfileAccessGroupMapping>();
            this.ZuttritProfilesTimeFrames = new HashSet<ZuttritProfilesTimeFrame>();
        }
    
        public long ID { get; set; }
        public Nullable<long> GroupID { get; set; }
        public int AccessProfileNo { get; set; }
        public string AccessProfileID { get; set; }
        public string AccessDescription { get; set; }
        public bool DisplayProfiles { get; set; }
        public string Memo { get; set; }
        public string ForeColour { get; set; }
        public string BackColour { get; set; }
    
        public virtual AccessGroup AccessGroup { get; set; }
        public virtual ICollection<AccessProfileAccessGroupMapping> AccessProfileAccessGroupMappings { get; set; }
        public virtual ICollection<ZuttritProfilesTimeFrame> ZuttritProfilesTimeFrames { get; set; }
    }
}
